### ISSUE TITLE
Problem in generating validating fiscal code with one vowel and one consonant

### ISSUE THREAD

**Issue by ShahzaibIbrahim** [okkam-it/fiscal-code-validator#25]
Upon doing research on the fiscal code. I have found that in Identifying short code of first/last name that contains less than 3 characters ("OM" (2) in this case).You are not handling the case of placing consonant before the vowel as per fiscal code generation algorithm. In this case M should come before O.

PRKMOX65D01Z222C --->Actual Code for a case
PRKOMX65D01Z222L --->Fiscal Generated By Current Code

**Comment by ShahzaibIbrahim** [comment]
I have fixed the issue and trying to create a pull request but it's throwing me 403 error for some reason.

**Comment by fpompermaier** [comment]
Let me check what's going on. I'll be back to you asap. Thanks

**Comment by fpompermaier** [comment]
I've just issued a PR from the security bot and I had no problem..if you still face problems just paste the diff here and I'll merge it for you

**Comment by fpompermaier** [comment]
Closed in #27
